### PR TITLE
Dev/cinemachine 3.0 UI related api changes

### PR DESCRIPTION
**Pull request by gaborkb**
[Delete any line or section that does not apply]

### Purpose of this PR

[JIRA issue. Desc of feature/change. Links to screenshots, design docs, user docs, etc. Remember reviewers may be outside your team, and not know your feature/area that should be explained more.]

### Testing status

[Explanation of what’s tested, how tested and existing or new automation tests. Can include manual testing by self and/or QA. Specify test plans. Rarely acceptable to have no testing.]

- [ ] Added an automated test
- [ ] Passed all automated tests
- [ ] Manually tested 

### Documentation status

[Overview of how documentation is affected by this change. If there is no effect on documentation, explain why. Otherwise, state which sections are changed and why.]

- [ ] Updated [CHANGELOG](https://keepachangelog.com/en/1.0.0/)
- [ ] Updated README (if applicable)
- [ ] Commented all public classes, properties, and methods
- [ ] Updated user documentation

### Technical risk

[Overall product level assessment of risk of change. Need technical risk & halo effect.]

### Comments to reviewers

[Info per person for what to focus on, or historical info to understand who have previously reviewed and coverage. Help them get context.]

### Package version

[Justification for updating either the patch, minor, or major version according to the [semantic versioning](https://semver.org/spec/v2.0.0.html) rules]

- [ ] Updated package version

### CODE REVIEW

**Comment by MechWarrior99** [comment]
Hey, so I happened to take a look at the github and saw that you are planning on making some API changes. 
I was wondering if you are going to the work to change some of the APIs, why not change them to be properties following the standard Unity naming scheme of using camelCase? Instead of just changing them to be differently named public fields?

**Comment by gaborkb** [comment]
> Hey, so I happened to take a look at the github and saw that you are planning on making some API changes. I was wondering if you are going to the work to change some of the APIs, why not change them to be properties following the standard Unity naming scheme of using camelCase? Instead of just changing them to be differently named public fields?

Yes, that is on our todo list, but we are going to do that last to avoid merge conflicts. :)

**Comment by MechWarrior99** [comment]
> Yes, that is on our todo list, but we are going to do that last to avoid merge conflicts. :)

Yay! Having the public fields has always bugged me so I am really happy to hear that! Best of luck! :D

**Comment by glabute** [comment]
No longer applicable

**Pull request closed without merging**
