### PR TITLE
CMCL-0000: Sample fixes

### PR DESCRIPTION
**Pull request by gaborkb**
### Purpose of this PR

- Added missing input in ThirdPerson Shooter.
- Instead of manipulating the Autodolly-FixedSpeed's Speed, the sample now contains a custom autodolly implementation: RandomizedRunnerSpeed.
RandomizedAutoDolly

### Testing status

- [ ] Added an automated test

- [ ] Passed all automated tests
- [x] Manually tested

### CODE REVIEW

**Review by glabute — CHANGES_REQUESTED** [review]
Scene is broken.  Runners don't run.  Restart Race button is gone.
That aside, the implementation is interesting.  It reveals the need for a Reset() method in ISplineAutoDolly.  I will add one.

Please make a separate fix for ThirdPersonShooter

**Comment by gaborkb** [comment]
Restart race button is gone because of the need for a Reset() method in ISplineAutoDolly. :)

**Comment by gaborkb** [comment]
Re-downloaded the samples in a new unity project and the scene is not broken for me. Runners run.

**Comment by gaborkb** [comment]
https://github.com/Unity-Technologies/com.unity.cinemachine/pull/737

**Pull request closed without merging**
