### PR TITLE
CMCL-1443: Solo mode should play the sequencer

### PR DESCRIPTION
**Pull request by glabute**
### Purpose of this PR

Sequencer was not playing when in Solo mode

### Testing status

- [ ] Added an automated test
- [ ] Passed all automated tests
- [x] Manually tested

### CODE REVIEW

**Comment by AntoineCharton** [comment]
Just wandering what if a user script relies on the state of the sequencer? What if someone want to see a state but in the middle of a sequence? Can we keep the solo button just changing which camera is focused and have an other button called solo play (Or a setting to disable it)?

**Comment by glabute** [comment]
> Just wandering what if a user script relies on the state of the sequencer

**Comment by AntoineCharton** [comment]
> > Just wandering what if a user script relies on the state of the sequencer
> 
> Not sure I understand this question.

As a user do you expect a button called "Solo" to do anything else than soloing the camera?

**Comment by glabute** [comment]
> As a user do you expect a button called "Solo" to do anything else than soloing the camera?

uh, no

**Review by gaborkb — APPROVED** [review]

**Pull request merged**
