### PR TITLE
Freelook prefab children are no longer visible.

### PR DESCRIPTION
**Pull request by gaborkb**
### Purpose of this PR

User reported some problems with freelook prefabs, when applying prefab modifications (Override -> Apply All).

1. The children can become visible. 
2. Data is lost.

I could reproduce #1, but not #2. 
I think #2 is a user error. I think this is what happens:
They modify parameter X on prefab instance A, then they modify parameter X on prefab instance B, and then they try to override all prefabs with Override -> Apply All from prefab instance B.
Instance A is not modified in this case, but this is the expected behaviour.

#1 is fixed by adding the HideChildren functionality to the prefab override callback.

https://forum.unity.com/threads/cinemachine-freelook-prefabs-seem-to-become-corrupted.532989/#post-7079488

### Testing status

- [ ] Added an automated test
- [ ] Passed all automated tests
- [x] Manually tested 

### Documentation status

- [x] Updated [CHANGELOG](https://keepachangelog.com/en/1.0.0/)
- [ ] Updated README (if applicable)
- [ ] Commented all public classes, properties, and methods
- [ ] Updated user documentation

### Technical risk

Low

### Comments to reviewers

I deleted SetChildrenFlag from UpdateRigCache. The reason is that I don't see a reason for setting the flags there. However, it is possible I overlooked something, and there is a case where this is needed.

### Package version

- [ ] Updated package version

### CODE REVIEW

**Review by glabute — CHANGES_REQUESTED** [review]
If I disable the FreeLook component in the prefab, then drag it into the scene, the child objects appear.  
image

**Comment by glabute** [comment]
Also try this:

image

then

image

**Comment by gaborkb** [comment]
> If I disable the FreeLook component in the prefab, then drag it into the scene, the child objects appear.
> image

Verified.
But also found a new case, when we already have prefab instances in the scene and we disable the prefab, some instances got their children visible. Solved it by adding SetFlagsForChildren in OnValidate()
OnDisable would be the logical way for me to put SetFlagsForChildren to, but unfortunately, at that stage the flags are correctly set. The flags get unset in "deserialization" which I think happens when the prefab is modified. That's why setting in OnValidate() solves it, because it gets called when "deserialization"  happens.

It seems like after calling SetFlagsForChildren in OnValidate(), there is no need to call it in Awake(). So I removed that. Please verify.

**Comment by gaborkb** [comment]
> Also try this:
> 
> image
> 
> then
> 
> image

Verified.

**Review by glabute — APPROVED** [review]

**Comment by glabute** [comment]
Huge improvement!  Good move putting it in OnValidate

**Pull request merged**
