### PR TITLE
CMCL-1436: Integration with the new Cameras Overlay in 23.2

### PR DESCRIPTION
**Pull request by thomas-tu**
### Purpose of this PR

Jira ticket: CST-1310

This PR adds allows the new Cameras Overlay to take control of Cinemachine Cameras, which is an Editor only feature. In summary:
- Cinemachine Cameras are visible and selectable from the Cameras Overlay.
- Selected Cinemachine Camera will have a preview shown on the Overlay.
- Users can look through the selected Cinemachine Camera within the SceneView.

This implementation doesn't take constraints into account.

image

Minimal supported version: Unity **23.2.0a14.**

### Testing status

[Explanation of what’s tested, how tested and existing or new automation tests. Can include manual testing by self and/or QA. Specify test plans. Rarely acceptable to have no testing.]

- [ ] Added an automated test
- [ ] Passed all automated tests
- [x] Manually tested 

### Documentation status

[Overview of how documentation is affected by this change. If there is no effect on documentation, explain why. Otherwise, state which sections are changed and why.]

- [ ] Updated [CHANGELOG](https://keepachangelog.com/en/1.0.0/)
- [ ] Updated README (if applicable)
- [ ] Commented all public classes, properties, and methods
- [ ] Updated user documentation

### Technical risk

Low. It's scoped to the Cameras Overlay and the Scene View.

### Package version

[Justification for updating either the patch, minor, or major version according to the [semantic versioning](https://semver.org/spec/v2.0.0.html) rules]

- [ ] Updated package version

### CODE REVIEW

**Review by glabute — APPROVED** [review]
LGTM, although I can't test it until the appropriate Unity version becomes available

**Comment by gaborkb** [comment]
I just finished building trunk unity, I am going to test it today or tomorrow.

**Comment by glabute** [comment]
There are some interesting edge-cases to look at.

For example, what if I have a vcam with no procedural motion on Position (allowing the scene-view camera to drag it), but has a rotation tracking enabled?  I would expect to be able to drag the camera's position, but while it's dragging the rotation should update so that it's always looking at the thing I'm tracking.  Currently, that doesn't happen, and I have to wait for a refresh after I stop dragging to get the updated rotation.

**Review by glabute — COMMENTED** [review]
Thomas, what are the controls to change the FOV and other lens properties via screen view?  I can't figure it out

**Review by glabute — APPROVED** [review]

**Pull request merged**
