### PR TITLE
CMCL-0000: Fix OrbitalFollow inappropriate vertical damping

### PR DESCRIPTION
**Pull request by glabute**
### Purpose of this PR

Bug:

Create the following:

- OrbitalFollow with default 3-ring setup.
- RotationComposer with large H and V damping (say 5 seconds).
- Follow target at player's feet, LookAt target at player's shoulder.
- Play scene, move mouse vertically: observe vertical damping is visible, not horizontal damping.

No damping should happen in response to mouse movement (only player movement).

This PR fixes that.  OrbitalFollow was calculating the damping bypass for the follow target when it should be for the lookat target.

### Testing status

- [ ] Added an automated test
- [ ] Passed all automated tests
- [x] Manually tested 

### Documentation status

- [x] Updated [CHANGELOG](https://keepachangelog.com/en/1.0.0/)
- [ ] Updated README (if applicable)
- [ ] Commented all public classes, properties, and methods
- [ ] Updated user documentation

### Technical risk

low

### CODE REVIEW

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.cinemachine?pullRequest=942) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.cinemachine?pullRequest=942) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/com.unity.cinemachine?pullRequest=942) it.</sub>

**Review by AntoineCharton — COMMENTED** [review]
The damping for the mouse seems accurate however the damping for the rotation doesn't look like 5 seconds. Is it expected?

Mar-08-2024 13-48-08

**Comment by glabute** [comment]
hmmmm nice catch!
Back to the drawing board with tis one....

**Comment by glabute** [comment]
Can't fix this

**Review by AntoineCharton — APPROVED** [review]
Makes more sense with the update you made.

**Pull request merged**
