### PR TITLE
CMCL-0000: Add FlyAround sample scene

### PR DESCRIPTION
**Pull request by glabute**
### Purpose of this PR
I'm tired of being asked on the forums about how to do a fly-around camera, so here is a sample that shows it.

### CODE REVIEW

**Comment by AntoineCharton** [comment]
Screenshot 2024-01-31 at 3 28 45 PM
Is it expected? 2023.2 hdrp input system.

Default material assigned to the fly around object.
Screenshot 2024-01-31 at 3 29 29 PM

**Comment by glabute** [comment]
The warning is fixed on the other PR.
Nice catch on the material

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.cinemachine?pullRequest=926) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.cinemachine?pullRequest=926) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/com.unity.cinemachine?pullRequest=926) it.</sub>

**Review by AntoineCharton — APPROVED** [review]
Very nice!

**Comment by glabute** [comment]
Did you have some issues about the control mappings?  Also, does it make sense on both keyboard/mouse and gamepad?

**Pull request merged**
