### PR TITLE
CMCL-0000: Update namespace to Unity.Cinemachine

### PR DESCRIPTION
**Pull request by AntoineCharton**
Change the namespace of Cinemachine

### Purpose of this PR

Change the namespace to align Cinemachine with the rest of unity.

### Testing status

- [x] Passed all automated tests
- [x] Manually tested 

### Documentation status

- [x] Updated [CHANGELOG](https://keepachangelog.com/en/1.0.0/)

### CODE REVIEW

**Comment by glabute** [comment]
You made the mistake of not using global find/replace to find namespaces.  Because of this, you missed some classes that were ifdef'ed out in your project.  You have to be careful with IDE "FindAllReferences" functions: they don't find things that are commented out.  That's why I prefer find/replace.

Also: I changed the namespace from "Cinemachine.Examples" to "Cinemachine.Samples", to match how it is in the assets.

**Comment by glabute** [comment]
Are you planning to do these renames?
- Tests -> Unity.Cinemachine.Tests
- Tests.Editor -> Unity.Cinemachine.Tests.Editor
- Tests.Runtime -> Unity.Cinemachine.Tests

**Comment by glabute** [comment]
I removed the Cinemachine.Utility namespace, as agreed in the slack thread

**Comment by AntoineCharton** [comment]
Nice findings! Added a task for later to make sure our CI coverage on compilation fails if CINEMACHINE_UGUI is not defined. CI should have failed in that case.

**Review by glabute — APPROVED** [review]

**Pull request merged**
