### PR TITLE
CMCL-0000: PrioritySettings Casting/Type Conversion Operators

### PR DESCRIPTION
**Pull request by Walter-Hulsebos**
### Purpose of this PR

This PR addresses the issue I raised #922 regarding the `PrioritySettings` struct. 
The main purpose is to enhance the usability and clarity of the API, particularly in the context of the recent 3.X.X API changes. This PR introduces custom operators for casting to/from `int` for the `PrioritySettings` struct, and updates the XML documentation to better guide developers through the API changes.

### Testing status

[Explanation of what’s tested, how tested and existing or new automation tests. Can include manual testing by self and/or QA. Specify test plans. Rarely acceptable to have no testing.]
I've made a modified copy of `PriorityTests.cs`, (`PriorityTestsImplicitCastingOperators.cs`) this is identical except it uses the custom operator instead. Let me know if more tests are required because this *doesn't* yet test casting to int, only from.

- [x] Added an automated test
- [x] Passed all automated tests
- [x] Manually tested 

### Documentation status

[Overview of how documentation is affected by this change. If there is no effect on documentation, explain why. Otherwise, state which sections are changed and why.]

- [ ] Updated CHANGELOG
- [x] Commented all public classes, properties, and methods
- [x] Updated user documentation

### Technical risk

The technical risk is considered low. 
The changes are an addition to the PrioritySettings struct and do not alter the pre-existing functionality of Cinemachine. The addition of implicit operators enhances the existing API without introducing breaking changes.

### Comments to reviewers

Reviewers should focus on the correctness of the implemented implicit operators, their tests and the clarity of the updated comments. Feedback on the comprehensibility of the changes from a user's perspective would be valuable.

A note: Perhaps it should explained in the comments that `PrioritySettings.Enabled` has to be true for it to work as well, or would that become too cluttered? It's explained in the `PrioritySettings` comments as well.

### CODE REVIEW

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.cinemachine?pullRequest=923) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.cinemachine?pullRequest=923) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/com.unity.cinemachine?pullRequest=923) it.</sub>

**Comment by Walter-Hulsebos** [comment]
I recognize that this is a particularly challenging period you, so I completely understand if you'd rather implement the changes yourself rather than directly implement and review this PR at this time.

If it's more convenient, I'm happy to provide a git PATCH file instead. This could streamline the process for you, allowing for easier integration of the changes.

**Review by AntoineCharton — COMMENTED** [review]
Very nice addition. Since it's an API addition it might need to land in a minor bump (3.1.X). @glabute what are your thoughts on that?

**Review by glabute — APPROVED** [review]
Nicely done

**Pull request merged**
