### PR TITLE
CMCL-0000: Check if installed Cinemachine is 3 or newer assembly definition

### PR DESCRIPTION
**Pull request by gaborkb**
### Purpose of this PR
LiveCapture team needs this (`CINEMACHINE_3_OR_NEWER`), so they can #if the public API that exposes our internal upgrader code. Similarly how I did it with HDRP, but HDRP luckily had a check that I could use.

### Testing status

- [ ] Added an automated test
- [ ] Passed all automated tests
- [x] Manually tested

### CODE REVIEW

**Review by glabute — APPROVED** [review]

**Comment by glabute** [comment]
I don't understand how this will work.  The define is only visible inside the CM assembly

**Comment by gaborkb** [comment]
> I don't understand how this will work. The define is only visible inside the CM assembly

Yes. They create an assembly reference to Cinemachine.Editor. Then they create a script that is going to see our internals, because it is within our assembly. This script now also sees this define.

**Comment by gaborkb** [comment]
@bechrifaAmine will test with this branch first. If all is good on their side, we can merge it.

**Comment by bechrifaAmine** [comment]
> @bechrifaAmine will test with this branch first. If all is good on their side, we can merge it.
It works, thank you

**Review by bechrifaAmine — APPROVED** [review]

**Pull request merged**
