### PR TITLE
CMCL-0000: Split tests in a separate package

### PR DESCRIPTION
**Pull request by guillaumelevass**
### Purpose of this PR

Use the .tests.json method to extract the tests in a new package. This means that we won't deliver tests with the next version of cinemachine. 

We decided it's the least of the two evils, between creating an empty tests in the main package or using CI magic to do the split. 

### Testing status

Passed isolation tests. Package is still ready to release.

### CODE REVIEW

**Review by AntoineCharton — APPROVED** [review]
Fixed the issue with the test. It was the dir of the package that was incorrect.
All good to me on the rest.

**Review by gaborkb — CHANGES_REQUESTED** [review]
2 tests failed

**Review by gaborkb — APPROVED** [review]

**Comment by gaborkb** [comment]
HDRPInputSystem failed.
I see this in the log:

[18:17:19.496 Information] [UPM-CI-UTILS] ERROR - Not all required packages were found in /home/bokken/build/output/Unity-Technologies/com.unity.cinemachine/upm-ci~/packages. Please clean up the folder and run 'upm-ci project pack' before running 'upm-ci project test'

**Comment by gaborkb** [comment]
This closes [the other unit test pr](https://github.com/Unity-Technologies/com.unity.cinemachine/pull/683), right?

**Pull request merged**
