### PR TITLE
Add clipper library as dependency to remove the conflicts with other …

### PR DESCRIPTION
**Pull request by ivan-trackman**
…packages already including the clipper library

### Purpose of this PR

To remove the hard embedded clipper library from the package, so it can be added as dependency.

### Testing status

- [YES] Manually tested 

### Documentation status

- [ ] Removed hard embedded clipper library, moved to dependency

### CODE REVIEW

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.cinemachine?pullRequest=402) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.cinemachine?pullRequest=402) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/com.unity.cinemachine?pullRequest=402) it.</sub>

**Comment by ivan-trackman** [comment]
Hi, I haven't realized prior to doing PR, but we're using our own package registry that translates nuget packages to unity packages, here is how it is in the manifest.json:
``` json
  "scopedRegistries": [
    {
      "name": "Perfect Parallel Unity NuGet",
      "url": "http://perfectparallel-unitynuget.azurewebsites.net",
      "scopes": [
        "org.nuget"
      ]
    }
  ],
```
Also our github fork: https://github.com/perfectparallel/UnityNuGet

maybe you can add it to the Unity registry somehow?
Ivan.

**Comment by mjmvisser** [comment]
@ivan-trackman what's the problem you're trying to solve, exactly? Are you having conflicts between our version of Clipper and one provided by a different package?

**Comment by glabute** [comment]
This issue is addressed and resolved elsewhere

**Pull request closed without merging**
