### PR TITLE
CMCL-0000: Spline roll cleanup

### PR DESCRIPTION
**Pull request by glabute**
### Purpose of this PR

Fixed a few issues in SplineRoll and splines in general:

- SplineRoll did not work properly when spline was scaled - especially with Distance units
- SplineRoll editor recalculates the spline railroad-track gizmo when rotations are modified in the inspector
- SplineRollTool.cs folded into SplineRollEditor.cs, with some refactoring for simplicity
- Added button in SplineRoll inspector to engage the scene view tool
- Prettier SplineRoll inspector: customized list view (implies minor API change)
- SplineRoll inspector must not support multi-select
- Added scene view tooltips to Spline Roll Tool
- Added ISplineReferencer interface to make SplineRoll more versatile
- Refactored roll cache in SplineCart and SplineDolly
- SplineCart and SplineDolly did not use the correct distances when distance units were used with scaled splines
- SplineCart and SplineDolly inspectors display errors if spline is a child object of these things
- Spline position in SplineCart and SplineDolly is now `[NoSaveDuringPlay]`

### Testing status

- [ ] Added an automated test
- [ ] Passed all automated tests
- [x] Manually tested 

### Notes to reviewer

A small API change was required to implement the prettier SplineRoll inspector.  In fact this is a good idea for cleanliness anyway, but it may be flagged as a breaking change.  We should make an exception for this, as it will break no client scripts.

### CODE REVIEW

**Comment by AntoineCharton** [comment]
May-29-2024 13-29-57
How do I make the camera rotate based on the roll?

**Comment by glabute** [comment]
Set this to "Spline":

image

**Review by AntoineCharton — COMMENTED** [review]
Applying offset + spline Container rotation causes camera jump.
May-29-2024 14-02-54
Screenshot 2024-05-29 at 2 04 23 PM

**Comment by glabute** [comment]
Not a bug, it's because your spline's tangent is discontinuous.  There is a jump even when offset is 0.

image

**Review by AntoineCharton — APPROVED** [review]
Tested:

- Rotating the spline
- Scaling uniformly and not uniformly
- Position of the spline not 0
- Normalized/distance/knot
- Damping
- Cinemachine Spline Roll (With the scene view integration)
- Rotation Composer (Screen position, Target Offset)

Any use case I may have missed?

**Comment by glabute** [comment]
Spline cart?

**Comment by AntoineCharton** [comment]
Screenshot 2024-05-29 at 3 52 19 PM

**Pull request merged**
