### PR TITLE
Performance Improvements

### PR DESCRIPTION
**Pull request by smitdylan2001**
### Purpose of this PR

Performance improvements

- Reorder vector calculations for performance
- Use TryGetComponent to reduce garbage allocations
- Merged if statements
- Use .SetPositionAndRotation for better performance
- String.IsNullOrEmpty instead of double checks
- Use static methods for performance
- Merge if statements with return
- Remove indirect .gameObject call

### Testing status

Tested basic cinemachine functionality without issue. No major code change.

### Technical risk

Low, no major code changes

### Package version

Not sure what to put here, since it's my first cinemachine PR. I can add package version if requested

### CODE REVIEW

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.cinemachine?pullRequest=551) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.cinemachine?pullRequest=551) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/com.unity.cinemachine?pullRequest=551) it.</sub>

**Review by gaborkb — CHANGES_REQUESTED** [review]
No need for changelog.

Thank you for these improvements.

**Comment by smitdylan2001** [comment]
> No need for changelog.
> 
> Thank you for these improvements.

Removed changelog changes.
Glad to help!
I hope some of these code changes can be followed for future code to keep the cinemachine snappy

**Review by smitdylan2001 — COMMENTED** [review]
Fixed in new commit

**Comment by glabute** [comment]
Thanks for this effort.
Pretty much all of these issues have been addressed in other commits, so I'm closing this.

**Comment by smitdylan2001** [comment]
> Thanks for this effort. Pretty much all of these issues have been addressed in other commits, so I'm closing this.

Also the .SetPositionAndRotation? 
These are a huge performance win

**Comment by glabute** [comment]
Yes

**Pull request closed without merging**
