### PR TITLE
CMCL-1579: add SaveDuringPlay confirmation dialog

### PR DESCRIPTION
**Pull request by glabute**
### Purpose of this PR

CMCL-1579: Add confirmation when exiting play mode is SaveDuringPlay is enabled and changes have been made.

image

### Testing status

- [ ] Added an automated test
- [ ] Passed all automated tests
- [x] Manually tested

### CODE REVIEW

**Comment by AntoineCharton** [comment]
Apr-04-2024 15-56-14
Is it supposed to pop it even if no changes were made?

**Comment by glabute** [comment]
>Is it supposed to pop it even if no changes were made?

Technically no.  Let me try to see why that's happening

**Comment by glabute** [comment]
Hah!  It was a stupid implementation.  Good catch.

I redid it, and now it always applies the changes, but if you select "cancel" in the dialog it just does an Undo for you.  So in fact you can still access the changes in that case by hitting Redo.

**Review by AntoineCharton — APPROVED** [review]
Awesome!

**Pull request merged**
