### PR TITLE
CMCL-1565: Deoccluder improvements, and add CinemachineShotQualityEvaluator

### PR DESCRIPTION
**Pull request by glabute**
### Purpose of this PR

1. Deoccluder: Work better with Position Composer/POV combo

Because with Position Composer, the camera is positioned after the aim, so the aim will be off if the camera gets repositioned by the extension.  

https://forum.unity.com/threads/cinemachinecollider-doesnt-work-when-body-is-framingtransposer.1524406/

2. Add CinemachineShotQualityEvaluator

This is a standalone version of the quality evaluation code in CinemachineDeoccluder, to use when you want evaluation but not the deoccluder

### Testing status

- [ ] Added an automated test
- [x] Passed all automated tests
- [x] Manually tested 

### Documentation status

- [x] Updated [CHANGELOG](https://keepachangelog.com/en/1.0.0/)
- [ ] Updated README (if applicable)
- [x] Commented all public classes, properties, and methods
- [x] Updated user documentation

### Technical risk

low

### CODE REVIEW

**Review by AntoineCharton — CHANGES_REQUESTED** [review]
Something is broke with Cinemachine Deocludder
Sep-15-2023 16-05-15

**Comment by glabute** [comment]
> Something broke with Cinemachine Deocludder. When I disable the deocluder the problem is gone. Tested with the deocluder sample. 
Fixed

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.cinemachine?pullRequest=899) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.cinemachine?pullRequest=899) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/com.unity.cinemachine?pullRequest=899) it.</sub>

**Review by AntoineCharton — APPROVED** [review]
Nice change. Retested and everything is working again

**Pull request merged**
