### PR TITLE
CMCL-0000: Improve game view dragging behaviour, some cleanup

### PR DESCRIPTION
**Pull request by glabute**
### Purpose of this PR

Game view guides behave better when dragged:
- If dead zone enabled, dead zone bars will only resize dead zone, not move it.
- If dead zone not enabled, dragging the bars will move screen position as expected.

Also some refactoring/cleanup

### CODE REVIEW

**Review by gaborkb — CHANGES_REQUESTED** [review]
I can still move the deadzone position if I start from e.g. size x = 0.5 and then pull it to 0. After it reaches 0 the position of the deadzone moves.

**Comment by glabute** [comment]
Can you be mor specific?  I can't make that happen from your description

**Comment by glabute** [comment]
There might be a very slight position movement from precision inaccuracies, but that was always happening, it's not new.

**Comment by glabute** [comment]
If you like, you can create a separate task to address that

**Pull request merged**
