### PR TITLE
Dev/cinemachine 3.0 UI tk

### PR DESCRIPTION
**Pull request by gaborkb**
[Delete any line or section that does not apply]

### Purpose of this PR

[JIRA issue. Desc of feature/change. Links to screenshots, design docs, user docs, etc. Remember reviewers may be outside your team, and not know your feature/area that should be explained more.]

### Testing status

[Explanation of what’s tested, how tested and existing or new automation tests. Can include manual testing by self and/or QA. Specify test plans. Rarely acceptable to have no testing.]

- [ ] Added an automated test
- [ ] Passed all automated tests
- [ ] Manually tested 

### Documentation status

[Overview of how documentation is affected by this change. If there is no effect on documentation, explain why. Otherwise, state which sections are changed and why.]

- [ ] Updated [CHANGELOG](https://keepachangelog.com/en/1.0.0/)
- [ ] Updated README (if applicable)
- [ ] Commented all public classes, properties, and methods
- [ ] Updated user documentation

### Technical risk

[Overall product level assessment of risk of change. Need technical risk & halo effect.]

### Comments to reviewers

[Info per person for what to focus on, or historical info to understand who have previously reviewed and coverage. Help them get context.]

### Package version

[Justification for updating either the patch, minor, or major version according to the [semantic versioning](https://semver.org/spec/v2.0.0.html) rules]

- [ ] Updated package version

### CODE REVIEW

**Comment by MechWarrior99** [comment]
I obviously don't know what the plan is internally. But to me it looks like you are switching to using UITK, but still trying to make it fit in with the API/architecture that Cinemachine 2.0 uses. If you are going to rewrite the UI in UITK, than to me as both a programmer and a user, it seems like it would make more sense to rearchitect it to follow more standard Unity conventions and the way that UITK is more 'meant' to be used.

Right now you have a base editor and you work by using attributes and specifying certain fields to draw differently or not to draw. This goes against how most things are done in Unity and also as someone who does a lot of editor tooling, this quite annoying to work with. While it generally does require more work/code to do, in the end it is normally a lot cleaner, allows for much easier flexibility and more follows the standard conventions in Unity for this sort of thing.

Again I don't know what the internal plans are or anything, but I wanted to make my thoughts/wishes known.

**Comment by gaborkb** [comment]
> I obviously don't know what the plan is internally. But to me it looks like you are switching to using UITK, but still trying to make it fit in with the API/architecture that Cinemachine 2.0 uses. If you are going to rewrite the UI in UITK, than to me as both a programmer and a user, it seems like it would make more sense to rearchitect it to follow more standard Unity conventions and the way that UITK is more 'meant' to be used.
> 
> Right now you have a base editor and you work by using attributes and specifying certain fields to draw differently or not to draw. This goes against how most things are done in Unity and also as someone who does a lot of editor tooling, this quite annoying to work with. While it generally does require more work/code to do, in the end it is normally a lot cleaner, allows for much easier flexibility and more follows the standard conventions in Unity for this sort of thing.
> 
> Again I don't know what the internal plans are or anything, but I wanted to make my thoughts/wishes known.

We agree. We are going to follow standard Unity, but this is just a very early version of the rewrite. Kind of a mock. We are going to the "proper" UITK rewrite, once some other refactors/changes are done.

Thank you for sharing your thoughts/wishes. They are welcome and noted 😉

**Comment by MechWarrior99** [comment]
> We agree. We are going to follow standard Unity, but this is just a very early version of the rewrite. Kind of a mock. We are going to the "proper" UITK rewrite, once some other refactors/changes are done.
> 
> Thank you for sharing your thoughts/wishes. They are welcome and noted 😉

Okay, that's great to hear! I just wanted to bring it up on the off chance that was not the plan.
I look forward to seeing the changes!

**Comment by krisrok** [comment]
I just wanted to throw my hat in the ring as well with a big 'yes please' ;) I'd love a UI for Cinemachine components that does not stand out as much as it does right now. In my opinion it still looks and feels like a third party plugin in many regards.

**Pull request closed without merging**
