### PR TITLE
CMCL-0000: auto-update targetgroup if needed for 2.9

### PR DESCRIPTION
**Pull request by glabute**
### Purpose of this PR

2.9 backport of #699 

- [ ] Added an automated test
- [ ] Passed all automated tests
- [x] Manually tested

### CODE REVIEW

**Review by gaborkb — COMMENTED** [review]
This somehow broke the tests.

Errors on yamato:
```
Script Compilation Problem at Library/PackageCache/com.unity.cinemachine@032d868fcd83/Runtime/Behaviours/CinemachineTargetGroup.cs
Library/PackageCache/com.unity.cinemachine@032d868fcd83/Runtime/Behaviours/CinemachineTargetGroup.cs(142,41): error CS8124: Tuple must contain at least two elements.
```

Maybe the projects need to be updated, because it is in PackageCache. 

I am going to check if it happens when I open one of the projects locally.

**Comment by gaborkb** [comment]
> This somehow broke the tests.
> 
> Errors on yamato:
> 
> ```
> Script Compilation Problem at Library/PackageCache/com.unity.cinemachine@032d868fcd83/Runtime/Behaviours/CinemachineTargetGroup.cs
> Library/PackageCache/com.unity.cinemachine@032d868fcd83/Runtime/Behaviours/CinemachineTargetGroup.cs(142,41): error CS8124: Tuple must contain at least two elements.
> ```
> 
> Maybe the projects need to be updated, because it is in PackageCache.
> 
> I am going to check if it happens when I open one of the projects locally.

These errors are because older editors don't support C# version 9. On release/2.9 maybe we should not use these. E.g. target-typed object initialization - `List<int> m_ValidMembers = new ();`.

**Comment by gaborkb** [comment]
On HDRP the tests fail, because they are not using the new time-invariant tests I think from CM3. So they should be disabled or we need to backport the tests from CM3.

**Comment by glabute** [comment]
Since these failures are not caused by this PR, we should approve this one and open up another to address the ci issues

**Pull request merged**
